language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 1.9.2
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - jruby-head
#  - ruby-head

# Branch white list
branches:
  only:
    - master
